name: Pull Request

on: [pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node v18.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 'v18.17.0'

      - name: Install packages
        run: yarn install --check-file

      - name: Unit tests
        run: yarn test

      - name: Build project
        run: yarn build
